language: python
python:
- '2.6'
- '2.7'
script: python setup.py test
deploy:
  provider: pypi
  user: acordiner
  password:
    secure: KrMBxbI/kCU6g9JeIHEcFAPUL6uQLahrHmhMj0LF2cBSZw52Ge8ErgRrwJf6p2spqA4JkFSYefSL63VqmiqotpoJehh5+ZemkX6A99xpz4lJ7ByBcP96/N9JzOEhdyxLJNLkU4XZRC2oxMGBo02qHLoAyiHjBZWS3Ad5x7w/1e0BohkTcKtzv3Gxc1easmiuqVZ22KFPaT8qSMTCbv0BEaCOf5Lp8zzc4SLWs1JTzFygotOJoO20sTudOoyOqplrGYFtAybsNGoZ4MwGwPgCZQeykJlzD5AtPrnb6WRqkX24D8dOq9RCFXVba9clrKAdtNVZIjlFjNLZrS5hQKUHt2S2nriKRu9nmhQoEFuRqcUvhLMlPhqKUkxTH1eWyoaWlV8XKMa2MF338eVBQaADoQgyfvoQa3uRzQMbWsrQWnRy5tUkT55J0+JCPWWJFXFvjKicws5TbU63kScEFnCqlpjv7M2Ent1+z3Bg4px5LanXBD5qkclRk5mYGyqTD9yYbBtEg0h3vSwTe3VEkg3zCHJSI1QIPtMHQB2EoQRvxCghFmzt8wnGmO71GEjSPneire6wx76j0yf5Qsgw9GCxH3HLTJbeggRXQ6fySKf98xHk//aaohvLNrhSn42lYNyXMX1NXl+eSdcymGIwGspxCO0LSKprijSKpJ3E3C6nXTg=
